

<?php
$title = 'Add new appointment';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php

// This provides a default CSS class and placeholder text for the patient name element:
$patientName = $form->get('patientName');
$patientName->setAttribute('class', 'form-control');
$patientName->setAttribute('placeholder', 'patientName');

// This provides a default CSS class and placeholder text for the appointment reason element:
$appoint = $form->get('reason');
$appoint->setAttribute('class', 'form-control');
$appoint->setAttribute('placeholder', 'Appointment reason');

// This provides a default CSS class and placeholder text for the start time element:
$startTime = $form->get('startTime');
$startTime->setAttribute('class', 'form-control');
$startTime->setAttribute('placeholder', 'Start time');

// This provides a default CSS class and placeholder text for the end time element:
$endTime = $form->get('endTime');
$endTime->setAttribute('class', 'form-control');
$endTime->setAttribute('placeholder', 'End time');

// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('appoint', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
      // label, element, and errors separately within ?>
<div class="form-group">
    <?= $this->formLabel($patientName) ?>
    <?= $this->formElement($patientName) ?>
    <?= $this->formElementErrors()->render($patientName, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($appoint) ?>
    <?= $this->formElement($appoint) ?>
    <?= $this->formElementErrors()->render($appoint, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($startTime) ?>
    <?= $this->formElement($startTime) ?>
    <?= $this->formElementErrors()->render($startTime, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($endTime) ?>
    <?= $this->formElement($endTime) ?>
    <?= $this->formElementErrors()->render($endTime, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();